description: >
  Набор имен процессов Windows (возможно и Linux), относящихся к играм и игровым лаунчерам.
  Правило необходимо для реализации специфических селекторов, позволяющих проксировать весь
  трафик игр через mihomo. Позволяет обходить внешние и внутренние блокировки определённых игр. 
author:
  username: VolodyaMEGAlodon
  github: https://github.com/VolodyaMEGAlodon