name: Create Release

on:
  workflow_run:
    workflows: ["Publish Rules to Release Branch"]
    types:
      - completed

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Checkout release Branch
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Install ZIP
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Archive Folders
        run: |
          echo "Archiving .mrs files..."

          for dir in */; do
            core_name="${dir%/}"

            if [[ -d "$core_name" && "$core_name" != .* ]]; then
              if find "$core_name" -type f -name '*.mrs' | grep -q .; then
                (cd "$core_name" && zip -qr "../${core_name}.zip" $(find . -type f -name '*.mrs' | sed 's#^./##'))
              fi
            fi

          done

          echo "Archives created:" && (ls -lh *.zip || echo "No archives were created.")

      - name: Generate release name
        id: release_info
        run: echo "name=$(openssl rand -hex 16)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: ${{ steps.release_info.outputs.name }}
          draft: false
          prerelease: false
          files: ./*.zip
          make_latest: true